### ISSUE TITLE
dsKeyToString (and maybe dsQueryToString) does NOT create unique ids

### ISSUE THREAD

**Issue by trollkotze** [sebelga/gstore-cache#4]
The cache-keys for cached entites, generated from their datastore paths, are not unique with the current method:

```/**
 * Convert a Google Datastore Key to a unique string id
 * It concatenates the namespace with the key path Array
 * @param {Datastore.Key} key The Google Datastore Key
 */
const dsKeyToString = (key, options = { hash: true }) => {
    if (typeof key === 'undefined') {
        throw new Error('Key cannot be undefined.');
    }
    let id = key.namespace || '';
    id += key.path.join('');
    return options.hash ? hashString(id) : id;
};
```

Simply concatenating the path elements can quite obviously result in multiple datastore entities being mapped to the same cache key.

Simple example `['zeng', 'arden']` and `['zen', 'garden']` (entity kind 'zen' or 'zeng', and entity name 'arden' or 'garden').

Simple solution: use any character that is not allowed in a datastore key path element as joinder, like `join(':')` instead of `join()`.

Not sure about `dsQueryToString`, have not checked what it produces. But looks similar.

**Comment by sebelga** [comment]
Hey, thanks for this. Yeah a character delimiter should fix this. :+1:

**Comment by sebelga** [comment]
Just release v1.0.1 that should avoid this. thanks 👍
